version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.12.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install 
          command: 'npm install'
      - run: 
          name: test
          command: 'npm test'
